<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
    <line>
      <![CDATA[<a href="C:\Users\Antonio\Desktop\kinderenvannu.jpg" target="_blank">Screenshot Link</a>]]>
    </line>
    <line>
      <![CDATA[<a href="C:\Users\Antonio\Desktop\kinderenvannu.jpg" target="_blank"><img height="200" width="200" src="C:\Users\Antonio\Desktop\kinderenvannu.jpg"</a>]]>
    </line>
  </reporter-output>
  <suite name="Functional Suite" duration-ms="94" started-at="2019-04-29T11:26:05Z" finished-at="2019-04-29T11:26:05Z">
    <groups>
    </groups>
    <test name="Validate Title Test" duration-ms="16" started-at="2019-04-29T11:26:05Z" finished-at="2019-04-29T11:26:05Z">
      <class name="testCases.TestCase2">
        <test-method status="FAIL" signature="validateTitles()[pri:0, instance:testCases.TestCase2@51cdd8a]" name="validateTitles" duration-ms="0" started-at="2019-04-29T13:26:05Z" finished-at="2019-04-29T13:26:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Yahoo.com] but found [Google.com],
	expected [false] but found [true],
	Failing the test as the condition is not met]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Yahoo.com] but found [Google.com],
	expected [false] but found [true],
	Failing the test as the condition is not met
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testCases.TestCase2.validateTitles(TestCase2.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="C:\Users\Antonio\Desktop\kinderenvannu.jpg" target="_blank">Screenshot Link</a>]]>
            </line>
            <line>
              <![CDATA[<a href="C:\Users\Antonio\Desktop\kinderenvannu.jpg" target="_blank"><img height="200" width="200" src="C:\Users\Antonio\Desktop\kinderenvannu.jpg"</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- testCases.TestCase2 -->
    </test> <!-- Validate Title Test -->
    <test name="Dependency test" duration-ms="16" started-at="2019-04-29T11:26:05Z" finished-at="2019-04-29T11:26:05Z">
      <class name="testCases.TestCase1">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testCases.TestCase1@59e5ddf]" name="launchBrowser" is-config="true" duration-ms="0" started-at="2019-04-29T13:26:05Z" finished-at="2019-04-29T13:26:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doUserReg()[pri:1, instance:testCases.TestCase1@59e5ddf]" name="doUserReg" duration-ms="0" started-at="2019-04-29T13:26:05Z" finished-at="2019-04-29T13:26:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="creatingDBCOnn()[pri:0, instance:testCases.TestCase1@59e5ddf]" name="creatingDBCOnn" is-config="true" duration-ms="0" started-at="2019-04-29T13:26:05Z" finished-at="2019-04-29T13:26:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatingDBCOnn -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testCases.TestCase1@59e5ddf]" name="launchBrowser" is-config="true" duration-ms="0" started-at="2019-04-29T13:26:05Z" finished-at="2019-04-29T13:26:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:testCases.TestCase1@59e5ddf]" name="doLogin" duration-ms="0" started-at="2019-04-29T13:26:05Z" depends-on-methods="testCases.TestCase1.doUserReg" finished-at="2019-04-29T13:26:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="creatingDBCOnn()[pri:0, instance:testCases.TestCase1@59e5ddf]" name="creatingDBCOnn" is-config="true" duration-ms="0" started-at="2019-04-29T13:26:05Z" finished-at="2019-04-29T13:26:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatingDBCOnn -->
      </class> <!-- testCases.TestCase1 -->
    </test> <!-- Dependency test -->
    <test name="Failure test" duration-ms="0" started-at="2019-04-29T11:26:05Z" finished-at="2019-04-29T11:26:05Z">
      <class name="testCases.TestFailure">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testCases.TestFailure@1877ab81]" name="setUp" is-config="true" duration-ms="16" started-at="2019-04-29T13:26:05Z" finished-at="2019-04-29T13:26:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCases.TestFailure@1877ab81]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-04-29T13:26:05Z" finished-at="2019-04-29T13:26:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TestFailure -->
    </test> <!-- Failure test -->
  </suite> <!-- Functional Suite -->
</testng-results>
